test var file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,6 +18,29 @@ env:
   GITHUB_BRANCH_NAME: ${{ github.ref_name }}
 
 jobs:
+  variables:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+        # working-directory: .aws/terraform
+    steps:
+      - name: Set ENV variables
+        run: |
+          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> vars.txt
+          if [[ $GITHUB_REF == refs/heads/main ]]; then
+            echo "Using QA Role"
+            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> vars.txt
+          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+            echo "Using Test Role"
+            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> vars.txt
+          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+            echo "Using Dev Role"
+            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> vars.txt
+          else
+            echo "Invalid branch name. Stopping the action."
+            exit 1
+          fi
   plan:
     runs-on: ubuntu-latest
     defaults:
@@ -28,121 +51,130 @@ jobs:
       - name: Git checkout
         uses: actions/checkout@v3
 
-      - name: Set ENV variables
+      - name: Get ENV Vars
         run: |
-          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
-          if [[ $GITHUB_REF == refs/heads/main ]]; then
-            echo "Using QA Role"
-            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
-          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
-            echo "Using Test Role"
-            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
-          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
-            echo "Using Dev Role"
-            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
-          else
-            echo "Invalid branch name. Stopping the action."
-            exit 1
-          fi
+          source ../../vars.txt
+          echo $AWS_ROLE
 
-      - name: Configure AWS credentials from AWS account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ env.AWS_ROLE }}
-          aws-region: ${{ env.AWS_REGION }}
-          role-session-name: GitHub-OIDC-TERRAFORM
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.2.5
+  #     - name: Git checkout
+  #       uses: actions/checkout@v3
 
-      - name: Terraform fmt
-        id: fmt
-        run: terraform fmt -check
-        continue-on-error: true
+  #     - name: Set ENV variables
+  #       run: |
+  #         echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
+  #         if [[ $GITHUB_REF == refs/heads/main ]]; then
+  #           echo "Using QA Role"
+  #           echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
+  #         elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+  #           echo "Using Test Role"
+  #           echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
+  #         elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+  #           echo "Using Dev Role"
+  #           echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
+  #         else
+  #           echo "Invalid branch name. Stopping the action."
+  #           exit 1
+  #         fi
 
-      - name: Terraform Init
-        id: init
-        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
+  #     - name: Configure AWS credentials from AWS account
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: ${{ env.AWS_ROLE }}
+  #         aws-region: ${{ env.AWS_REGION }}
+  #         role-session-name: GitHub-OIDC-TERRAFORM
 
-      - name: Terraform Workspaces
-        id: workspaces
-        run: |
-          chmod +x ../../.github/workflows/utils/workspaces.sh
-          source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.2.5
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #     - name: Terraform fmt
+  #       id: fmt
+  #       run: terraform fmt -check
+  #       continue-on-error: true
 
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color
-        continue-on-error: true
+  #     - name: Terraform Init
+  #       id: init
+  #       run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #     - name: Terraform Workspaces
+  #       id: workspaces
+  #       run: |
+  #         chmod +x ../../.github/workflows/utils/workspaces.sh
+  #         source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
 
-  apply:
-    needs: plan
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: .aws/terraform
-    steps:
-      - name: Git checkout
-        uses: actions/checkout@v3
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform validate -no-color
 
-      - name: Set ENV variables
-        run: |
-          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
-          if [[ $GITHUB_REF == refs/heads/main ]]; then
-            echo "Using QA Role"
-            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
-          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
-            echo "Using Test Role"
-            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
-          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
-            echo "Using Dev Role"
-            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
-          else
-            echo "Invalid branch name. Stopping the action."
-            exit 1
-          fi
+  #     - name: Terraform Plan
+  #       id: plan
+  #       run: terraform plan -no-color
+  #       continue-on-error: true
 
-      - name: Configure AWS credentials from AWS account
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ env.AWS_ROLE }}
-          aws-region: ${{ secrets.AWS_REGION }}
-          role-session-name: GitHub-OIDC-TERRAFORM
+  #     - name: Terraform Plan Status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.2.5
+  # apply:
+  #   needs: plan
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: .aws/terraform
+  #   steps:
+  #     - name: Git checkout
+  #       uses: actions/checkout@v3
 
-      - name: Terraform Init
-        id: init
-        env:
-          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
-          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
-        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
+  #     - name: Set ENV variables
+  #       run: |
+  #         echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
+  #         if [[ $GITHUB_REF == refs/heads/main ]]; then
+  #           echo "Using QA Role"
+  #           echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
+  #         elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+  #           echo "Using Test Role"
+  #           echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
+  #         elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+  #           echo "Using Dev Role"
+  #           echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
+  #         else
+  #           echo "Invalid branch name. Stopping the action."
+  #           exit 1
+  #         fi
 
-      - name: Terraform Workspaces
-        id: workspaces
-        env:
-          GITHUB_BRANCH_NAME: ${{ github.ref_name }}
-        run: |
-          chmod +x ../../.github/workflows/utils/workspaces.sh
-          source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
+  #     - name: Configure AWS credentials from AWS account
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: ${{ env.AWS_ROLE }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
+  #         role-session-name: GitHub-OIDC-TERRAFORM
 
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.2.5
 
-      - name: Terraform Apply
-        run: terraform apply -auto-approve -input=false
+  #     - name: Terraform Init
+  #       id: init
+  #       env:
+  #         AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
+  #         AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
+  #       run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}" -backend-config="workspace_key_prefix=${REPO_NAME}" -backend-config="role_arn=${AWS_TF_ROLE}"
+
+  #     - name: Terraform Workspaces
+  #       id: workspaces
+  #       env:
+  #         GITHUB_BRANCH_NAME: ${{ github.ref_name }}
+  #       run: |
+  #         chmod +x ../../.github/workflows/utils/workspaces.sh
+  #         source ../../.github/workflows/utils/workspaces.sh $GITHUB_BRANCH_NAME
+
+  #     - name: Terraform Validate
+  #       id: validate
+  #       run: terraform validate -no-color
+
+  #     - name: Terraform Apply
+  #       run: terraform apply -auto-approve -input=false
