update workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,60 +19,60 @@ env:
 
 jobs:
   build:
-      runs-on: ubuntu-latest
-      defaults:
-        run:
-          shell: bash
-          working-directory: src/backend
-      steps:
-        - name: Git checkout
-          uses: actions/checkout@v3
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+        working-directory: src/backend
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v3
+      - name: Variables
+        run: |
+            echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
+            if [[ $GITHUB_REF == refs/heads/main ]]; then
+              echo "Using QA Role"
+              echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
+              echo "ENV=qa" >> $GITHUB_ENV
+            elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+              echo "Using Test Role"
+              echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
+              echo "ENV=test" >> $GITHUB_ENV
+            elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+              echo "Using Dev Role"
+              echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
+              echo "ENV=dev" >> $GITHUB_ENV
+            else
+              echo "Invalid branch name. Stopping the action."
+              exit 1
+            fi
+            echo ${REPO_NAME,,}
 
-      run: |
-          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
-          if [[ $GITHUB_REF == refs/heads/main ]]; then
-            echo "Using QA Role"
-            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
-            echo "ENV=qa" >> $GITHUB_ENV
-          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
-            echo "Using Test Role"
-            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
-            echo "ENV=test" >> $GITHUB_ENV
-          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
-            echo "Using Dev Role"
-            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
-            echo "ENV=dev" >> $GITHUB_ENV
-          else
-            echo "Invalid branch name. Stopping the action."
-            exit 1
-          fi
-          echo ${REPO_NAME,,}
+      - name: Setup python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
 
-        - name: Setup python
-          uses: actions/setup-python@v4
-          with:
-            python-version: '3.12'
+      - name: Install and package Python dependencies
+        run: |
+          mkdir -p zips
+          declare -a dirs=("auth" "url" "mosaify" "option")
+          for dir in "${dirs[@]}"; do
+            pip install --quiet -r "./${dir}/requirements.txt" -t "${dir}_python"
+            cd "${dir}_python" || exit
+            zip -q -r -g "../zips/${dir}.zip" .
+            cd ..
+            cd "${dir}" || exit
+            zip -q -g "../zips/${dir}.zip" "${dir}.py"
+            cd ..
+          done
 
-        - name: Install and package Python dependencies
-          run: |
-            mkdir -p zips
-            declare -a dirs=("auth" "url" "mosaify" "option")
-            for dir in "${dirs[@]}"; do
-              pip install --quiet -r "./${dir}/requirements.txt" -t "${dir}_python"
-              cd "${dir}_python" || exit
-              zip -q -r -g "../zips/${dir}.zip" .
-              cd ..
-              cd "${dir}" || exit
-              zip -q -g "../zips/${dir}.zip" "${dir}.py"
-              cd ..
-            done
-
-        - name: Upload artifact for deployment job
-          uses: actions/upload-artifact@v2
-          with:
-            name: python_deployment
-            path: src/backend/zips
-            if-no-files-found: error
+      - name: Upload artifact for deployment job
+        uses: actions/upload-artifact@v2
+        with:
+          name: python_deployment
+          path: src/backend/zips
+          if-no-files-found: error
             
   plan:
     needs: build
