fix syntax

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,25 +30,25 @@ jobs:
 
       - name: Variables
         run: |
-            echo WORKSPACE_NAME=$(python ../../.github/workflows/utils/branch_mapping.py "$GITHUB_BRANCH_NAME") >> $GITHUB_ENV
-            echo "GREETING=Hello" >> $GITHUB_ENV
-            echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
-            if [[ $GITHUB_REF == refs/heads/main ]]; then
-              echo "Using QA Role"
-              echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
-              echo "ENV=qa" >> $GITHUB_ENV
-            elif [[ $GITHUB_REF == refs/heads/develop ]]; then
-              echo "Using Test Role"
-              echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
-              echo "ENV=test" >> $GITHUB_ENV
-            elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
-              echo "Using Dev Role"
-              echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
-              echo "ENV=dev" >> $GITHUB_ENV
-            else
-              echo "Invalid branch name. Stopping the action."
-              exit 1
-            fi
+          echo WORKSPACE_NAME=$(python ../../.github/workflows/utils/branch_mapping.py "$GITHUB_BRANCH_NAME") >> $GITHUB_ENV
+          echo "GREETING=Hello" >> $GITHUB_ENV
+          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
+          if [[ $GITHUB_REF == refs/heads/main ]]; then
+            echo "Using QA Role"
+            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
+            echo "ENV=qa" >> $GITHUB_ENV
+          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+            echo "Using Test Role"
+            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
+            echo "ENV=test" >> $GITHUB_ENV
+          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+            echo "Using Dev Role"
+            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
+            echo "ENV=dev" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name. Stopping the action."
+            exit 1
+          fi
 
       - name: Configure AWS credentials from AWS account
         uses: aws-actions/configure-aws-credentials@v1
