download artifacts to plan job

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,36 +51,45 @@ jobs:
             path: src/backend/zips
             if-no-files-found: error
             
-  # plan:
-  #   needs: build
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #       working-directory: .aws/terraform
-  #   steps:
-  #     - name: Git checkout
-  #       uses: actions/checkout@v3
+  plan:
+    needs: build
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+        working-directory: .aws/terraform
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v3
 
-  #     - name: Set ENV variables
-  #       run: |
-  #         echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
-  #         if [[ $GITHUB_REF == refs/heads/main ]]; then
-  #           echo "Using QA Role"
-  #           echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
-  #           echo "ENV=qa" >> $GITHUB_ENV
-  #         elif [[ $GITHUB_REF == refs/heads/develop ]]; then
-  #           echo "Using Test Role"
-  #           echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
-  #           echo "ENV=test" >> $GITHUB_ENV
-  #         elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
-  #           echo "Using Dev Role"
-  #           echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
-  #           echo "ENV=dev" >> $GITHUB_ENV
-  #         else
-  #           echo "Invalid branch name. Stopping the action."
-  #           exit 1
-  #         fi
+      - name: Set ENV variables
+        run: |
+          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
+          if [[ $GITHUB_REF == refs/heads/main ]]; then
+            echo "Using QA Role"
+            echo "AWS_ROLE=${{ secrets.AWS_QA_ROLE }}" >> $GITHUB_ENV
+            echo "ENV=qa" >> $GITHUB_ENV
+          elif [[ $GITHUB_REF == refs/heads/develop ]]; then
+            echo "Using Test Role"
+            echo "AWS_ROLE=${{ secrets.AWS_TEST_ROLE }}" >> $GITHUB_ENV
+            echo "ENV=test" >> $GITHUB_ENV
+          elif [[ $GITHUB_REF == refs/heads/feature/* || $GITHUB_REF == refs/heads/bugfix/* || $GITHUB_REF == refs/heads/task/* || $GITHUB_REF == refs/heads/hotfix/* ]]; then
+            echo "Using Dev Role"
+            echo "AWS_ROLE=${{ secrets.AWS_DEV_ROLE }}" >> $GITHUB_ENV
+            echo "ENV=dev" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name. Stopping the action."
+            exit 1
+          fi
+
+        - name: Download artifact from build job
+          uses: actions/download-artifact@v2
+          with:
+            name: python_deployment
+            path: .aws/terraform/
+
+        - name: View directory
+          run: ls
 
   #     - name: Configure AWS credentials from AWS account
   #       uses: aws-actions/configure-aws-credentials@v1
